### ISSUE TITLE
Implementation of rain water trapping problem in C++

### ISSUE THREAD

**Issue by suprajaLara** [sumanthst24/Code_Repo#5]
#4 
@sumanthst24 
Trapping Rain Water is a basic array implementation problem. 

Problem Description: Given n non-negative integers representing an elevation map where the width of each bar is 1.

Write a program to compute how much water it is able to trap after raining.

Input: arr[]   = {3, 0, 2, 0, 4}
Output: 7
Explanation:
We can trap "3 units" of water between 3 and 2,
"1 unit" on top of bar 2 and "3 units" between 2 
and 4.

**Comment by sumanthst24** [comment]
Submit the above one in a file

**Comment by suprajaLara** [comment]
#7 -> link to pull request
@sumanthst24
