### ISSUE TITLE
Random Program 

### ISSUE THREAD

**Issue by ysubha** [sumanthst24/Code_Repo#6]
vector<string> subStringsKDist(string inputStr, int num)
{
    vector<string>s ;	        
     int a [26] ,l[num], len = inputStr.length();
     int o=-1;
     string sub ="",sub1 ="";
  
 
             for (int i=0;i<26;i++)
                    a[i]=-1;
            for (int j= 0;j<len;j++)
            {
                char letter = inputStr[j];
               o=(int)letter-97;
               /*  cout<<(letter);
                cout<<o;*/
                a[o]=o;
                
            }
              
             for (int i=0;i<26;i++)
                 { //cout<<(char)(a[i]+97);
                    char c=(char)(a[i]+97);
                    if(c!='`')
                    {
                        sub+=c;
                        
                    }
                     
                 
                 }
                 for(int k=0;k<len;k++)
                 {
                       for(int p=0;p<num;p++)
                        {
                            l[p]=rand()%sub.length();
                            int y=l[p];
                             for(int g=0;g<num;g++)
                             {
                                // l[g]=rand()%sub.length();
                                 while(l[g]==y)
                                    { l[g]=rand()%sub.length();}
                             }
                              sub1+=(char)sub[l[p]];
                        } 
                     sub1+=(char)sub[rand()%sub.length()];
                    
                        }
                         cout<<sub1<<"\t";
                         sub1="";
                 }
                //cout<<sub;
         
   
    
    return s;
}

**Comment by sumanthst24** [comment]
You should submit the code in a file

**Comment by ysubha** [comment]
Develop link to Repository (Random Code )(https://github.com/sumanthst24/Code_Repo/files/4772800/Untitled-1.-.Copy.txt)

**Comment by sumanthst24** [comment]
Make a pull request for the same
